### ISSUE TITLE
Release naming scheme is incompatible with RPM builds

### ISSUE THREAD

**Issue by samcmill** [xalt/xalt#10]
Minor issue: `rpmbuild` expects the package to be named `xalt-<version>.tar.gz`, whereas the packages available from https://github.com/xalt/xalt/releases are named `<version>.tar.gz`.

```
$ rpmbuild -tb /tmp/2.7.tar.gz ...
error: File /tmp/xalt-2.7.tar.gz: No such file or directory
```

Renaming the file works around the issue.

**Comment by rtmclay** [comment]
XALT now uses tags that are of the form *xalt-X.Y.Z* instead of *X.Y.Z*

**Comment by rtmclay** [comment]
O.K. to close this ticket?
