### ISSUE TITLE
xalt not capturing SLURM job_id

### ISSUE THREAD

**Issue by jstrelka** [xalt/xalt#12]
I am using xalt v2.7.3 on a test cluster running SLURM. We are successfully tracking xalt_run data for our submitted jobs. Though we are not able to capture the SLURM job_id when a batch job is submitted using sbatch. If we create a user interactive environment using salloc however, xalt is capturing the job_id successfully. If there is any insight or direction for rectifying the issue I would appreciate the input. 

Thank you in advance for any help submitted.

**Comment by jstrelka** [comment]
When we run an salloc job translate.C processes in the SLURM queueType. However, when we run sbatch jobs translate.C processes through the else statement with an unknown queueType. 
I tested by placing a flag string in the job_id assignment under the else statement in translate.C.

I also printed the environments for both my sbatch and salloc jobs and they looked identical besides the salloc environment has the variable SLURM_PTY_WIN_COL.

**Comment by rtmclay** [comment]
Are you telling me that SLURM_JOB_ID is set in both cases?

**Comment by jstrelka** [comment]
Yes SLURM_JOB_ID is set in both cases.

**Comment by rtmclay** [comment]
I am wondering if your sbatch case is somehow clearing the environment.  For example scons is known to wipe the environment.  Does using sbatch always cause XALT's job_id to be unknown for even simple examples.

**Comment by rtmclay** [comment]
Anything new to report?

**Comment by jstrelka** [comment]
Hey I will be back in the office tomorrow morning. I have been out for the holiday. Sorry on the delay.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jstrelka** [comment]
Hey rtmclay thank you for your assistance we have the job id tracking with sbatch jobs now. I found the test cluster environment to be slightly different than production. Thanks!
