### ISSUE TITLE
Description of json data

### ISSUE THREAD

**Issue by wirawan0** [xalt/xalt#15]
Hi,

I wonder if anyone has written documentation or notes on the meaning of the fields in the json records produced by XALT. I could not find that in the current documentation. If not, please take this as a feature request so that data analysts can get started more quickly.

Thanks,
Wirawan

**Comment by rtmclay** [comment]
An interesting question.  XALT json format was designed to just be a way to transfer data between the linking and execution of programs on a system and the mysql database.  I guess I feel that the key-value pairs are self-explanatory.  So if more detail is of interest, then please add a file in the docs/source directory to be part of the xalt.readthedocs.org documentation.  If there are fields in the json record that are not clear please let me know and I'll try to write an explanation for individual fields.

**Comment by rtmclay** [comment]
Please look at the documentation at xalt.readthedocs.org and in particular:

https://xalt.readthedocs.io/en/latest/120_xalt_json.html

Does this help with understanding the Json that XALT generates?

**Comment by rtmclay** [comment]
O.K. to close this issue?

**Comment by wirawan0** [comment]
The doc link above is indeed helpful. Before closing this issue, let me ask several things that may help me find out the meaning of fields:

* Looks like all table names end with "T"? But some have "DT" suffix, what does that mean? I noted that some names end up with "A" (e.g. `cmdlineA`)--that looks like arrays to me.

* Which files in the xalt source are relevant for me to look first? Maybe not all of the pertinent files, if there are so many of them. At least so I can get a good starting point. I can uncover the rest.

Thanks,
Wirawan

**Comment by rtmclay** [comment]
You are correct.  I use the convention that hash table/dictionaries end in a cap T and arrays end in a cap A.  The table userDT entries used to be part of the userT table but it became useful to separate them into a string part and a numerical part.  So the userDT table is the data part (i.e. numerical part) of the userT table. 

The xalt_initialize.c file and some other less important files become the libxalt_init.so library that attaches to each executable.  If an executable is being tracked then myinit() or myfini() makes a system call to the "xalt_run_submission" program.  This program is responsible for generating the run   *.json record.  The programs calls routines like buildUserT() (found in src/buildUserT.C) and parseProcMaps() in src/parseProcMaps.C.  It should be clear from there.
