### ISSUE TITLE
Configuring XALT to track various libraries: such as Java

### ISSUE THREAD

**Issue by jstrelka** [xalt/xalt#16]
I have been trying to track libraries usage and have not been successful. My config file is pointing to various java libraries the same way I pointed at bin executables. Below is a sample line from my config.py file:
    ['KEEP',  r'.*\/Java\/1.8.0_121\/jre\/lib\/*'],

*** There is a asterisk at the beginning and end of the line and a backslash preceding each forward slash in the path above.****

My test script imports java.math.* which is located under the jre/lib directory in a .jar file. 

Thank you in advance for any advice.

**Comment by rtmclay** [comment]
Right.  This is not going to work with XALT in its current state.  XALT only knows about libraries that are linked in by the build process.  It knows nothing about dynamically linked libraries. For example on our Stampede2 cluster has a java installed:

```
staff.s2(3003)% ldd /bin/java
        linux-vdso.so.1 =>  (0x00007ffffffc8000)
        /opt/apps/xalt/xalt/lib64/libxalt_init.so (0x00002ae163d22000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ae163f4e000)
        libz.so.1 => /lib64/libz.so.1 (0x00002ae16416a000)
        libjli.so => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ae164380000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ae164584000)
        /lib64/ld-linux-x86-64.so.2 (0x00002ae163afe000)
staff.s2(3004)% java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```
XALT will track all those libraries (except libxalt_init.so never recorded) So libraries like libc.so and libdl.so are recorded.  But java dynamically pulls in libraries to satify the "import java.math.*" requests in your test code.  They are not tracked.

Now it might be possible to track those libraries.  We currently to something that captures those imports for R.  So java may have a way to hook in to the "import" code and let XALT track those libraries.  I just don't know how to do that.  I know how to track imports for R, matlab and I am working on Python.  If you or anyone knows how to "hook" into the java import code then it could be supported.

**Comment by jstrelka** [comment]
Thank you rtmclay for taking the time to outline xalt's library tracking functionality. 
So XALT will currently track the libraries linked in the build process for any library dependent application? And to track libraries linked in the build process, how would I go about configuring XALT to do so? Do I point to them as if they were a bin executables with a 'KEEP'? 

I am unaware of how to hook Java's "import" code. My working knowledge of Java is fairly limited.

**Comment by rtmclay** [comment]
XALT automatically tracks the libraries.  There is no need to mark the libraries as "KEEP".  My knowledge of java is limited as well.
