### ISSUE TITLE
Not enough info about DB structure

### ISSUE THREAD

**Issue by DavVad** [xalt/xalt#17]
Is there any documentation concerning MySQL DB structure that is storing data obtained by XALT? For example, it is currently not clear how xalt_object table is related to xalt_link and xalt_run, or why xalt_run stores several records for the job with 1 job_id, etc.
I have found design manual for XALT version 0.5, but many things have noticeably changed in XALT2 we are currently trying to use.

Thanks in advance!

**Comment by rtmclay** [comment]
Please see the documentation found at xalt.readthedocs.org and especially: 

https://xalt.readthedocs.io/en/latest/110_db.html

to see if this update to the documentation answers your questions.

**Comment by rtmclay** [comment]
I am closing this issue.  If you have question you can re-open this issue or create a new one.
