### ISSUE TITLE
Binary present under cmdline in XALT MySQL database. 

### ISSUE THREAD

**Issue by jstrelka** [xalt/xalt#18]
Hello,

We are tracking binaries on our system using syslog functionality of Xalt. We ship the logs from a file using the XALT decrypting script a to the MySQL database. However, under the xalt_run table there is a cmdline field that still has some encoded binary. What is this binary referring to? Is it possible to drop the field at the time of shipping the logs to MySQL so the cmdline field never makes it into MySQL?

Thanks!

**Comment by rtmclay** [comment]
To save space in the db, XALT compresses the command line text.  To extract it you'll need to do:
```
select uncompress(cmdline) from xalt_run;
```
inside mysql.

**Comment by jstrelka** [comment]
Okay, is there a way to drop the cmdline field from making it to the database. We do not need the cmdline information and would like to save the record space of not having it.

Thanks.

**Comment by jstrelka** [comment]
Thank you!
