### ISSUE TITLE
API Overwriting issue

### ISSUE THREAD

**Issue by mdong** [xalt/xalt#19]
Hi Guys,

I found a somewhat absurd issue with API overwriting. My user was having issue with antechamber from Amber, and after some research I determined that xalt + odd naming in antechamber is causing the issue.

From tracing I found that xalt will perform a/some hostname lookup, done through libresolv, I think it in xalt_syshost. This is pretty normal usually, but inside Amber, their developer created a function called "connect":

```
// AmberTools/src/antechamber/rotate.c

int connect(char *connect_file, int atomnum, ATOM * atom, int *bondnum, BOND * bond, int maxbond)
```

So when libresolv try to do its business, it create socket, and it try to connect, instead of calling the actually connect from libc, it called this function instead. 

I understand this is not a issue for xalt, I should probably email Amber developer to suggest maybe change the function name. But it does make me wonder if there is anyway in xalt to ensure all call made by xalt lands on where it intended to go? I only aware of way like dlsym, but that seems need to be done on every function, which will be pretty annoy, do you guys have any good ideas on this? 

Best,
Min Dong

**Comment by rtmclay** [comment]
In this particular case, I have moved the call to xalt_syshost() out of the xalt shared library that gets linked to user code. Please try XALT-2.7.13 to see if it fixes this problem for you.  Thanks very much for the bug report.

**Comment by mdong** [comment]
Thank you very much for the quick response, I can confirm that XALT-2.7.13 solved the issue. The binary from amber could executable without any problem.

Thank you for all the good work ^_^
