### ISSUE TITLE
Running XALT's `ld` without arguments produces an executable

### ISSUE THREAD

**Issue by vkarak** [xalt/xalt#23]
If XALT's `ld` wrapper is invoked without arguments, it produces an `a.out`. I would expect the behaviour to be compliant with that of the system linker, so for example produce an `ld: no input files` error message.

**Comment by rtmclay** [comment]
Please test the new XALT 2.7.20 when you get the chance.  I have added code to XALT's ld wrapper so that when there are zero arguments, the wrapper calls the real ld so that it can produce the error  and exit with a non-zero status.

**Comment by vkarak** [comment]
Hi @rtmclay, we are going to install 2.7.23 and let you know.

**Comment by rtmclay** [comment]
Closing this ticket.  Feel free to reopen if this issue re-appears.
