### ISSUE TITLE
Install directory hierarchy and prefix

### ISSUE THREAD

**Issue by samcmill** [xalt/xalt#25]
XALT interprets `--prefix` to be the "base" install directory.  For instance, `--prefix /opt` would install XALT in `/opt/xalt/<version>`.  In fact, XALT complains if the prefix contains the version, prompting for the wonderfully named `--with-IrefuseToInstallXALTCorrectly=yes` option if that's what you really really want to do.

In https://github.com/easybuilders/easybuild-easyconfigs/pull/9792, I would like to install XALT in a directory like `/opt/easybuild/software/xalt/2.7.27-gpu`, but there is not a way to specify this since `$PKGV` (== `xalt/<version>`) is automatically tacked on the "base" install directory.

I don't know the history for the strictness on the installation directory, but I'm wondering if it would be possible to add an option to specify the subdirectory name (`$PKGV`).  Something like `--subdir=xalt/2.7.27-gpu`, where the default value would be `xalt/<version>`?

**Comment by rtmclay** [comment]
The GPU support works correctly even if there is no GPU hardware on a node so I don't understand why you would want a separate GPU version.  This is what we do on frontera which has nodes that do and do not have GPU's.

The reason why XALT if configured with --prefix=/opt and installs XALT in /opt/xalt/<version> and makes a symlink between /opt/xalt/xalt and /opt/xalt/<version> is for the following reasons:

1. It is expected that there will only one version of XALT installed at a time
2. But there may be multiple versions of XALT installed over the life of the machine.
3. Programs built with a previous version of XALT better still work.
4. XALT builds a shared library libxalt_init.so or if there are static binaries.  then XALT code is part of 
    the executable.
5. The XALT code that works with executables  is split into two parts.  The part in libxalt_init.so which is written in C.  This C code makes a system call to a C++ program to generate the *.json records that end up in a database.
6. The C++ code needs to be in a "fixed" location for the life of the machine so any program built with an older version of XALT can still find this C++ program. 

This is why all version of XALT expect that if --prefix=/opt then XALT is installed in /opt/xalt/<version> and the directory "/opt/xalt/xalt/libexec" is ALWAYS there.

This may or may not explain why XALT works the way it does. But this has to factor into any solution.

**Comment by samcmill** [comment]
Building the GPU version requires the NVML header, or essentially CUDA.  Once it's built, it runs whether there is or isn't GPUs.

I'm trying to save the EasyBuild step of installing CUDA if someone wants to install XALT without GPU support.

Just thinking out loud... could an environment variable control where to find the C++ code, defaulting to the fixed location where XALT was originally installed?  The XALT environment module could set this new variable?

**Comment by samcmill** [comment]
With the addition of the `--with-siteControlledPrefix` option in 2.7.29, this can be closed.
