### ISSUE TITLE
Xalt Signal handling

### ISSUE THREAD

**Issue by mdong** [xalt/xalt#27]
Hi Guys, 

I just had a user reporting cuda-gdb segfault on our system. Older version seems to be fine, 8.0 for instance, but since 9.0 cuda-gdb will segfault on start. After some investigation i think it is caused by xalt installing signal handling that caused this issue. 

If using regular gdb, it will report custom handler preinstalled. But with cuda-gdb, it will just segfault.

I studied xalt source code a little bit, and i found:

XALT_SIGNAL_HANDLER
 
Setting no to this variable resolved my issue, but i don't seems to recall ever sew it in the document, maybe this is an added feature at some point and never documented?

Also, if my understanding is correct, xalt signal handling actually perform quite important work. I wonder, if it is possible to create a hook in xalt to replace default libc "int sigaction(int signum, const struct sigaction *act, struct sigaction *oldact);" implementation. When the original program call sigaction, xalt performs check within the hook, if it is an action in signalA then just call the original handler in the end of wrapper_for_myfini instead of raise it?

Best,
Min Dong

**Comment by rtmclay** [comment]
XALT Signal Handling as been removed from XALT.  Its main goal was to capture the output when a long running job terminated by the job scheduler (like SLURM).  This does not work with MPI programs. So I have removed it.  I am closing this issue for this reason.
