### ISSUE TITLE
Statically link libexec programs

### ISSUE THREAD

**Issue by samcmill** [xalt/xalt#28]
The XALT libexec tools are dynamically linked against libstdc++, libgcc_s, etc.

If XALT is built using a compiler more recent than the default system compiler, e.g., the user has a compiler environment module loaded, then the XALT libexec tools may depend on symbol versions not available in the system libstdc++, etc.  Then if the compiler environment module is not loaded at runtime (likely), XALT will not work correctly.

One option is to statically link all XALT programs with libstdc++, etc.  Is there any reason not to statically link with libstdc++, etc.?  Or alternatively copy libstdc++, etc. to XALT's lib directory similar to how libuuid, etc. are already handled.

This popped up in https://github.com/easybuilders/easybuild-easyconfigs/pull/9792#issuecomment-631248656.  

cc @boegel

**Comment by rtmclay** [comment]
As I said in the easy build ticket.  It is a mistake to build XALT with anything but the system gcc.

**Comment by samcmill** [comment]
Understood.  But I think there would other benefits to statically linking, such as container compatibility.  For example, if the host system is Centos 8 (GNU 8.3) and that's used to build XALT, but the container is based on Centos 7 (GNU 4.8).

**Comment by rtmclay** [comment]
Right but the static libraries are not installed.  On a ubuntu box and a Centos 7 box do not have libstdc++.a installed.  I have run into problems where static versions of libuuid.a are just not supplied.  That is why I went with copying to libraries to the XALT install directory.

**Comment by samcmill** [comment]
Is also copying libstdc++, etc. an option?

**Comment by rtmclay** [comment]
Sure but it is not just libstdc++.  I worry about libc.so etc.  There are 48 shared libraries linked to my version of xalt_run_submission.  Do we need to copy every one?

**Comment by kmanalo** [comment]
Thanks @samcmill I overlooked reading this issue in detail.

Adding my query from the XALT users about `xalt_run_submssion` running inside a Singularity container:
https://sourceforge.net/p/xalt/mailman/xalt-users/thread/EF78E31E-63C8-4DD0-A1FB-B1ABB8D0CBB1%40gatech.edu/#msg37017334

I would also vote for static linking for container compatibility as mentioned in https://github.com/xalt/xalt/issues/28#issuecomment-631736231

**Comment by rtmclay** [comment]
It is not possible to guarantee that all the libraries that xalt_run_submission etc need are available in a static lib*.a version.  So instead XALT copies over the system libraries into the lib64 install directory and handles the appropriate rpath'ing and setting LD_LIBRARY_PATH correctly where needed. 

Please test XALT version 2.8.2 to see if it works for you.

**Comment by rtmclay** [comment]
I found a bug in XALT 2.8.2 on Centos 7.  Please test XALT 2.8.3

Thanks,

**Comment by kmanalo** [comment]
I dropped back to using the original container that did not have `libssh2.so.1`

Before inside the container:
```
Singularity> /path/to/my/packages/xalt/xalt/libexec/xalt_run_submission
/path/to/my/packages/xalt/xalt/libexec/xalt_run_submission: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory
```

Currently inside the Singularity container: 
```
Singularity> /path/to/my/packages/xalt/xalt/libexec/xalt_run_submission
/path/to/my/packages/xalt/xalt/libexec/xalt_run_submission: relocation error: /path/to/my/packages/xalt/2.8.3/lib64/libpthread.so.0: symbol __libc_dl_error_tsd version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

How configured:
```
./configure --with-syshostConfig=env_var:LMOD_SYSHOST \
 --with-transmission=syslog --with-trackGPU=yes \
 --with-etcDir=/path/to/my/modules/ \
 --prefix=/path/to/my/packages \
 --with-MySQL=no --with-config=/some/site_config.py
```

**Comment by kmanalo** [comment]
@rtmclay 

You likely have something far more robust in mind for XALT containers and non-containers alike, but here's my existing workaround based on examining the implementation of `find_required_libraries.py` to solve the issue for this ONE container.

I tried to fiddle with other combinations of library blacklists, but my experiments ended up not working out so well...  Instead, I ended up including what I needed for the container, specifically `libssh2` and `libssl` by creating a whitelist lib structure.

```
includeT = {
  "libssh2"     : True,
  "libssl"      : True
}      
```

Then I substituted ` if (my_name in includeT):` in place of `if (not( my_name in ignoreT)):`.

Separately, when running XALT_TRACE I saw `LD_LIBRARY_PATH` pointing to something like 

```
LD_LIBRARY_PATH="/usr/local/pace-apps/manual/packages/lib64" .. xalt_run_submission ...
```
That should point to `LD_LIBRARY_PATH="/usr/local/pace-apps/manual/packages/xalt/xalt/lib64"` right?

**Comment by rtmclay** [comment]
Thanks very much for analysis of the problem.  You are correct that I did not set LD_LIBRARY_PATH correctly in all cases.  This has been fixed in my tests. Please test XALT 2.8.4 to see if it works for you.

**Comment by kmanalo** [comment]
The LD_LIBRARY_PATH points correctly for me with XALT 2.8.4

**Comment by rtmclay** [comment]
Please test XALT-2.9.9 to see if it works better with containers.
