### ISSUE TITLE
No rule to make target `/usr/local/xalt/2.8.8/site_packages', needed by `Inst_site_py'.

### ISSUE THREAD

**Issue by morrone** [xalt/xalt#30]
I am attempting to build xalt 2.8.8 from this git repo.  My configure line looks like:

```
./configure \
            --with-syshostConfig=strip_nodename_numbers \
            --with-config=Config/TACC_config.py \
            --with-transmission=file \
            --with-trackScalarPrgms=no \
            --with-trackGPU=no \
            --with-functionTracking=no \
            --with-MySQL=no
```

Then when I try to build I get:

```
$ DESTDIR=<somepath> make install
cd <somepath>/usr/local/xalt/2.8.8/lib;                        \
        rm -f x86_64-linux-gnu i386-linux-gnu;      \
        ln -s ../lib64 x86_64-linux-gnu;            \
        ln -s . i386-linux-gnu
make: *** No rule to make target `/usr/local/xalt/2.8.8/site_packages', needed by `Inst_site_py'.  Stop.
```

By the way, it is a little frustrating that there is not a default "make" target that just builds xalt without performing the installation step.

**Comment by rtmclay** [comment]
I had an unnecessary '/' between $(DESTDIR) and $(SITE_PKG_DIR).  I will modify the Makefile system to support an "all" target that just builds at a later date.

**Comment by rtmclay** [comment]
The latest fix should fix your issue.  Please test xalt-2.8.10.

**Comment by rtmclay** [comment]
I looked at the way that that the Makefile works with XALT.  It doesn't make sense to have "make all" target that just builds the libraries and then a separate "make install" target.  XALT builds the libraries and places the stuff directly into the install directory.

**Comment by morrone** [comment]
Thanks! It does build for me now.
