### ISSUE TITLE
Silence XALT output to terminal

### ISSUE THREAD

**Issue by weijianwen** [xalt/xalt#32]
I found that XALT prints verbose messages which may confuse HPC users. Is it possible to silence XALT output and just work on the background.

Thank you!

**Comment by rtmclay** [comment]
XALT is usually very quiet.  What version are you using and what output are you seeing?  Normally XALT only generates output if export XALT_TRACING=yes otherwise it is silent unless there are some accidental debugging statements that got released.

**Comment by weijianwen** [comment]
My fault. I followed tutorials on https://xalt.readthedocs.io/en/latest/ and considered `XALT_TRACING=yes` as a prerequisite to make XALT work. Disabling this environment variable solves my issue.

It would be great if an environment variable list available in the document so users don't need to grep names in XALT source code.

**Comment by rtmclay** [comment]
I have updated the docs to include a description of the env. vars that XALT uses: https://xalt.readthedocs.io/en/latest/095_xalt_env_vars.html
