### ISSUE TITLE
Failed to build XALT on MySQL server due to UnicodeDecodeError

### ISSUE THREAD

**Issue by weijianwen** [xalt/xalt#33]
I followed https://xalt.readthedocs.io/en/latest/060_setup_db.html to setup a database for XALT . Building failed with the following error messages:

```
VERSION=2.9.8
Use contrib argparse... no
checking for library containing SHA1... -lcrypto
checking for library containing curl_easy_setopt... -lcurl
Traceback (most recent call last):
  File "./proj_mgmt/py_build_tools/build_xalt_interval_table.py", line 138, in <module>
    if ( __name__ == '__main__'): main()
  File "./proj_mgmt/py_build_tools/build_xalt_interval_table.py", line 112, in main
    exec(open(args.confFn).read(), namespace)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 356: ordinal not in range(128)
```

Steps and the configuration file are attached. I appreciate if any advice is given.

Steps to reproduce this issue on CentOS 7.8
---------------------------------------------

```
# yum groupinstall -y 'Development Tools'
# yum install -y Lmod libcurl-devel elfutils-libelf-devel git libuuid-devel kernel-headers openssl-devel
# yum install -y MySQL-python python2-PyMySQL python27-MySQL-python python36-PyMySQL python36-mysql
# git clone https://github.com/xalt/xalt.git
# cd xalt  
# git checkout xalt-2.9.8
# wget https://raw.githubusercontent.com/SJTU-HPC/xalt-conf/master/sjtupi2_config.py -o Config/sjtupi2_config.py
# ./configure --prefix=/opt \
--with-syshostConfig=hardcode:sjtupi \
--with-systemPath=/usr/bin:/bin:/usr/local/bin \
--with-trackScalarPrgms=yes \
--with-trackGPU=no \
--with-functionTracking=no \
--with-MySQL=yes \
--with-config=Config/sjtupi2_config.py
# make install
```

[sjtupi2_config.py.txt](https://github.com/xalt/xalt/files/5166514/sjtupi2_config.py.txt)

**Comment by rtmclay** [comment]
I am unable to reproduce this error. I used your configuration file (sjtupi2_config.py).  I even tried having the xalt repo in a directory with non-ascii character.  Is the directory that it failed have a non-ascii character in the name?

**Comment by rtmclay** [comment]
I was able to build a docker container of a Centos 7.8 run your example.  The command: 

wget https://raw.githubusercontent.com/SJTU-HPC/xalt-conf/master/sjtupi2_config.py -o Config/sjtupi2_config.py

didn't work correctly for me but I was able to do: 

   cd Config ;wget https://raw.githubusercontent.com/SJTU-HPC/xalt-conf/master/sjtupi2_config.py

and get it to work.  It still might be that the directory you have xalt in has non-ascii characters which is causing the problem. Please let me know the absolute path of where the xalt directory is.

**Comment by rtmclay** [comment]
Here is the version of the container I ran:
```
[root@b845357e408e xalt]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core


```

**Comment by weijianwen** [comment]
My fault again. wget `-o` option is for logging, not for output file redirection. Using `-O` instead resolves this issue.

Thank you!
