### ISSUE TITLE
How to load *.json results via xalt_file_to_db.py

### ISSUE THREAD

**Issue by weijianwen** [xalt/xalt#34]
I followed https://xalt.readthedocs.io/en/latest/070_loading_json_by_file.html to load *.json results into the database. I got confused at reading "Create Script to load json records into the database" since it doesn't specify json file names nor directory names. I didn't know how to specify the location. Did I missing something?

Thank you.

```
#!/bin/bash

# get lock, quit if lock is unavailable
# set trap to clear lock if this script aborts.

~swtools/xalt/xalt/sbin/xalt_file_to_db.py --delete      \
  --confFn  ~swtools/process_xalt/xalt_<dbname>_db.conf  \
  --reverseMapD ~swtools/process_xalt/reverseMapD

# remove lock
```

**Comment by rtmclay** [comment]
Thanks for the question.  I have updated https://xalt.readthedocs.io/en/latest/070_loading_json_by_file.html.  As the updated docs say, you configure XALT on the system and the swtools account the same with respect to --with-transmission=file and probably  --with-xaltFilePrefix="...". This way the `xalt_file_to_db.py` knows about where the *.json files are located.

**Comment by weijianwen** [comment]
Thank you. I noticed a similar issue #11  in which I noticed the configuration option `--with-xaltFilePrefix` . Better if a link to https://xalt.readthedocs.io/en/latest/050_install_and_test.html?highlight=with-xaltFilePrefix#creating-xalt-directories-when-using-with-xaltfileprefix is presented in that section.
