### ISSUE TITLE
Questions on roles in XALT settings

### ISSUE THREAD

**Issue by weijianwen** [xalt/xalt#35]
Following https://xalt.readthedocs.io/en/latest/ to setup XALT on our cluster, I got a bit confused about roles in XALT settings. In a setting where "file transfer" is used, there seems to be following roles with XALT installed:

Role 1. Compiling or compute nodes, where XALT is launched to hijack linking then generates JSON records.
Role 2. A MySQL VM host, where XALT initializes the database.
Role 3. A JSON record reader, where XALT parse JSON records then stores them into MySQL.

Please correct me if I am wrong. Several more things to confirm:

1. Regarding Role 2 above,  https://xalt.readthedocs.io/en/latest/060_setup_db.html#setup-the-database instructs users to install XALT into a VM co-existing with MySQL. I think it is unnecessary as long as the XALT instance can access the MySQL instance.
2. Still regarding Role 2 above, XALT has done its work after initializing the database and is never invoked. Is that right?
3. Can Role 2 and Role 3 above merge into one XALT instance?

Thank you!

**Comment by rtmclay** [comment]
You don't have to install XALT on the VM as long as you access the VM's mysql instance remotely, You can create the DB remotely.  

You do not need XALT "installed" on the VM in the sense of collecting user program execution data.  You only need XALT on the VM for the administration of the XALT DB if you wish to do things locally on the VM.

I believe that you mean: Can role 1 and role 3 be merged into one install? and not role 2 and role 3.  Roles 1 and 3 are on the same cluster where as Role 2 is on a separate VM computer.

Role 3 requires an install of mysql where as Role 1 doesn't.  As long as you are willing to install mysql libraries everywhere on your login (compiling) and compute nodes then you do not need a private install of XALT to make role 3 happen.  It is just that it is a private install on one account where you need the mysql libraries and commands.

Our clusters use local disks, so we try to minimize what gets stored on the local disk.  If your site uses a shared global location then this is less of a problem.

**Comment by weijianwen** [comment]
Thank you for the explanation @rtmclay .  I'll install XALT on two places with a shared file system between them:

1. Compute nodes without MySQL libraries.
2. A separate node with MySQL libraries.
