### ISSUE TITLE
JSON records are NOT loaded into the database

### ISSUE THREAD

**Issue by weijianwen** [xalt/xalt#39]
I followed instructions on https://xalt.readthedocs.io/en/latest/070_loading_json_by_file.html , but failed to load JSON records into the database. Any suggestion is welcome. Thank you!

Expected results
-----------------

JSON records are loaded into the database then deleted. Records can be found in the database.

Actual results
--------------

JSON records are NOT loaded into the database and still there. Records cannot be found in the database.

Steps to reproduce this issue
------------------------------

1. Use XALT to generate JSON records.
2. Configure XALT on a node access to both JSON records and the database.
3. Run `/opt/xalt/xalt/sbin/xalt_file_to_db.py --delete --confFn /etc/xalt/xaltdb_db.conf  --reverseMapD /lustre/share/reverseMapD` to load JSON records.

```
# # /opt/xalt/xalt/sbin/xalt_file_to_db.py --delete \
>     --confFn /etc/xalt/xaltdb_db.conf  \
>     --reverseMapD /lustre/share/reverseMapD

num links:  0 , num pkgs:  0 , num runs:  0

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      0.0                    0.0
ALL MPI               0.0                    0.0
MPI    < 15 mins      0.0                    0.0
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0
```

The JSON record directory is show as follows. One of the JSON file is attached.
[run.sjtupi.2020_11_05_22_58_01_3459.hpc-jianwen.zzz.783e9492-34f4-4c1a-8a21-5e0d0d15cacb.json.txt](https://github.com/xalt/xalt/files/5500374/run.sjtupi.2020_11_05_22_58_01_3459.hpc-jianwen.zzz.783e9492-34f4-4c1a-8a21-5e0d0d15cacb.json.txt)

```
# tree /lustre/archive/XALT/
/lustre/archive/XALT/
├── 555
│   └── run.sjtupi.2020_11_05_22_58_01_3459.hpc-jianwen.zzz.783e9492-34f4-4c1a-8a21-5e0d0d15cacb.json
└── 673
    └── run.sjtupi.2020_11_05_16_25_11_6711.hpc-jianwen.zzz.85dd87e7-0ff2-46fb-8cf8-8d1b02ebbebc.json
```

**Comment by rtmclay** [comment]
On my system I was able to ingest your *.json file so the generation of that file is correct.  To see what the xalt_file_to_db.py file is doing. So please change your command to ingest the files to:
```
/opt/xalt/xalt/sbin/xalt_file_to_db.py --delete --report_file --confFn /etc/xalt/xaltdb_db.conf --reverseMapD /lustre/share/reverseMapD 
```
It is the same command except that the --report_file option has been added.  Also include the top part from 
```
    $ xalt_configuration_report
```

**Comment by rtmclay** [comment]
The issue may be that `/opt/xalt/xalt/sbin/xalt_file_to_db.py` finding the json files.  I have updated XALT to version xalt-2.9.12.  Please test xalt-2.9.12 because there is some new debugging information.

**Comment by weijianwen** [comment]
Thank you, @rtmclay . It is my fault. I updated XALT to 2.9.12 then resolve this issue with help of debugging information. It turn out that `xaltFilePrefix=` is incorrectly specified to XALT on the digesting node. Now the JSON records have been loaded into the database then deleted.

```
################################################################
Using XALT_FILE_PREFIX: "/lustre/archive/XALT", XALT_USERS: "<empty>"
################################################################

/lustre/archive/XALT/555/run.sjtupi.2020_11_05_22_58_01_3459.hpc-jianwen.zzz.783e9492-34f4-4c1a-8a21-5e0d0d15cacb.json
+/lustre/archive/XALT/673/run.sjtupi.2020_11_05_16_25_11_6711.hpc-jianwen.zzz.85dd87e7-0ff2-46fb-8cf8-8d1b02ebbebc.json
num links:  0 , num pkgs:  0 , num runs:  2

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      1.0              4523.6089
ALL MPI               1.0               553.9867
MPI    < 15 mins      1.0               553.9867
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0
```
