### ISSUE TITLE
Querying signal handlers in python returns None instead of SIG_DFL

### ISSUE THREAD

**Issue by jonathaneichelberger** [xalt/xalt#4]
```python
from __future__ import print_function
import signal
print(signal.getsignal(signal.SIGINT))
```
Without xalt produces: `<built-in function default_int_handler>` 
With xalt produces: `None`

This is an issue when packages (or even built-in python libraries) attempt to set their own signal handlers (or perhaps ignore certain signals) and then restore the original signal handlers (which you cannot restore to None) before completing.

For example, I imagine you have users who use `dask` and `distributed` in python. The following would produce an error (it uses python's built-in multiprocessing.forkserver library deep down, which sets and restores signal handlers):
```python
from distributed import Client()
c = Client()
```

The only workaround I have discovered thus far is to set the environment variable `XALT_SIGNAL_HANDLER` to `no`, which I understand prevents stop records from being produced under certain situations (e.g., pressing ctrl-c).

Are you registering your own custom signal handler, or are you setting signal handlers to `NULL`? If they're being set to `NULL`, I believe it would make more sense to set them to `SIG_DFL` instead; the code at the top would then produce `0` or `Handlers.SIG_DFL`. If not, is there any other work around other than the setting of that environment variable; what are the implications of not generating stop records as a result? Thanks.

**Comment by rtmclay** [comment]
What version of XALT are you running?

**Comment by jonathaneichelberger** [comment]
@rtmclay I'm running version 2.6.5.

**Comment by rtmclay** [comment]
I have upgraded XALT to version 2.6.10.  In this version I have removed SIGINT but have kept many others.  I believe that I have setup XALT's signal handler correctly.  Is is possible that python doesn't understand a custom handler and reports None?  In any event,  the code which sets the signal handler and processes it is in src/xalt_initialize.c at lines 703 to 734:

```
  v = getenv("XALT_SIGNAL_HANDLER");
  if (!v || strcmp(v,"no") != 0)
    {
      int signalA[] = {SIGHUP, SIGQUIT, SIGILL,  SIGTRAP, SIGABRT, SIGBUS, 
		       SIGFPE, SIGSEGV, SIGTERM, SIGXCPU, SIGUSR1};
      int signalSz  = N_ELEMENTS(signalA);
      struct sigaction action;
      struct sigaction old;
      memset(&action, 0, sizeof(struct sigaction));
      action.sa_handler = wrapper_for_myfini;
      for (i = 0; i < signalSz; ++i)
        {
          int signum = signalA[i];
          sigaction(signum, NULL, &old);
          if (old.sa_handler == NULL)
            sigaction(signum, &action, NULL);
        }
    }
}
void wrapper_for_myfini(int signum)
{
  struct sigaction action;
  memset(&action, 0, sizeof(struct sigaction));
  sigemptyset( &action.sa_mask);
  action.sa_handler = SIG_DFL;
  sigaction(signum, &action, NULL);
  myfini();
  raise(signum);
}
```

In particular, in the wrapper_for_myfini(), the code creates a new signal handler which has a default signal handler then it re-raises the signal.   Comments?

**Comment by jonathaneichelberger** [comment]
It is possible python doesn't understand custom handlers and reports None. Removing SIGINT has at least solved the issue above. Thank you.
