### ISSUE TITLE
Json to database is only possible as root

### ISSUE THREAD

**Issue by adityakavalur** [xalt/xalt#42]
Thanks for developing this code! It's a pretty handy tool.
However, I ran into a issue when developing a workflow for deployment. Currently the workflow of moving json records to the database is only possible as `root`. I'd think that facilities would want to manage as much as possible at the user level. There is a user-level epilog for job-step and jobs in slurm (not sure about other schedulers) which would be a good place for data movement. However, the user is not aware of the record that was just written. Additionally, since sites likely have $XALT_FILE_PREFIX as writeable only, the directory will not be searchable either. A possible solution would be a index of json records for each user that can be referenced to obtain paths to the json records that are sort of obfuscated through the `hashV`.

**Comment by rtmclay** [comment]
I have a some comments about how this might work:

1. Why not use the SYSLOG or curl methods of transport?
2. Could the database server handle all the requests?
3. Since a slurm job might have several executions happening where would a list of XALT result files go?
4. About the only way I see the file method could support epilog doing this would be to make $XALT_FILE_PREFIX be dynamic or use ~/.xalt.d and have prolog make sure that ~/.xalt.d or $XALT_FILE_PREFIX exists and then have epilog cleanup the *.json files.  This only makes sense if the database server could handle the load.

**Comment by adityakavalur** [comment]
Hi @rtmclay thanks for your reply, regarding the points you raised.

1. I have not looked at the feasibility of syslog or curl, let me get back to you on this. NERSC has a builtin mechanism for moving json files to elasticsearch in omni, which is what I was hoping to leverage. This, I believe, should be able to handle the load, although we will need to stress test. The primary motivation is to run as little as possible with elevated privilege accounts.
2. For the index approach, it is possible to have an option to add the index option at time of configuration. Your approach of $HOME/.xalt.d sounds secure and feasible. An index file(s) can store the path to the $XALT_FILE_PREFIX/hashV/ and the slurm job id, thereby reducing the search time. An alternative approach is to have a $XALT_INDEX/$USER directory, however, we will have to consider security implications of that.
3. An unaddressed issue I see in the above approach is that it does not address builds on login nodes, which will still require a manual movement. However, I imagine the number of records generated through these jobs is negligible compared to runs.

**Comment by rtmclay** [comment]
Well, I will look at any pull requests you create. All json records are sent through src/util/transmit.c.   I know that other sites do use curl to talk to elasticsearch.

**Comment by adityakavalur** [comment]
Thanks @rtmclay . I will close this issue and work on a PR.
