### ISSUE TITLE
JSON records are NOT loaded into the database

### ISSUE THREAD

**Issue by gcpmendez** [xalt/xalt#45]
I found a similar problem like solved but a little different .. 

I followed instructions on https://xalt.readthedocs.io/en/latest/070_loading_json_by_file.html , but failed to load JSON records into the database:

$ xalt_file_to_db.py --confFn  /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf 

################################################################
XALT Git Version: xalt-2.10.3
  Using XALT_FILE_PREFIX: "/root/.xalt.d"
################################################################

num links:  0 , num pkgs:  0 , num runs:  0

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      0.0                    0.0
ALL MPI               0.0                    0.0
MPI    < 15 mins      0.0                    0.0
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0 

when I add the argument --report_file I can see the json files.

I'm using the last version.

Regards ;)

**Comment by rtmclay** [comment]
Is this a container?  If so, you need to set the user name.

**Comment by gcpmendez** [comment]
its not a container. 

I attach you one json example:
[json_example.txt](https://github.com/xalt/xalt/files/6419795/json_example.txt)

**Comment by rtmclay** [comment]
Thanks for sending me an example *.json file! I was able to read in your example record into the database. So as far as I can tell your record is correct.  I have modified the xalt_file_to_db.py file to  add debug information.  Please install xalt-2.10.4 and try:

```
$ xalt_file_to_db.py -D --confFn /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf
```

This should hopefully explain why you are not storing records.

**Comment by gcpmendez** [comment]
I attach you the output:

[log.txt](https://github.com/xalt/xalt/files/6426116/log.txt)

**Comment by rtmclay** [comment]
Based on the output and looking at xalt_file_to_db.py, I believe that the problem is that you do not have read access to the *.json files.  I did miss a case where the program returns with no comment.  I have changed that in my copy.

Please check that you can print the files out to the screen from the user you are trying to ingest the *.json files.

**Comment by gcpmendez** [comment]
the user is root.

**Comment by rtmclay** [comment]
Did you do the following?

Please check that you can print the files out to the screen from the user you are trying to ingest the *.json files.

**Comment by gcpmendez** [comment]
I can do it

I'm testing with root and the user gpaz.
I have the directory .xalt.d in each one.

From root when I execute the command ./xalt_file_to_db.py --report_file --confFn /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf I obtained:
``
./xalt_file_to_db.py --report_file --confFn /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf 

################################################################
XALT Git Version: xalt-2.10.4
  Using XALT_FILE_PREFIX: "USE_HOME"
################################################################

/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.aaa.44f598d4-c881-432d-8000-0daa4a53de7d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.zzz.44f598d4-c881-432d-8000-0daa4a53de7d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.aaa.72d7980c-0dac-494c-8217-9a3b2f27804d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.zzz.72d7980c-0dac-494c-8217-9a3b2f27804d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.aaa.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.zzz.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.aaa.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.zzz.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.aaa.5e73d269-77a1-4603-9874-f209a20f4d99.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.zzz.5e73d269-77a1-4603-9874-f209a20f4d99.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.aaa.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
---/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.aaa.44f598d4-c881-432d-8000-0daa4a53de7d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.zzz.44f598d4-c881-432d-8000-0daa4a53de7d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.aaa.72d7980c-0dac-494c-8217-9a3b2f27804d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.zzz.72d7980c-0dac-494c-8217-9a3b2f27804d.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.aaa.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.zzz.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.aaa.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.zzz.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.aaa.5e73d269-77a1-4603-9874-f209a20f4d99.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.zzz.5e73d269-77a1-4603-9874-f209a20f4d99.json
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.aaa.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
------+---------+---------+----------+---------|-/home/gpaz/.xalt.d/run.teidehpc.2021_05_05_15_22_10_8029.gpaz.aaa.6aa4ab67-a896-4a98-a141-a87d221d68ff.json
/home/gpaz/.xalt.d/run.teidehpc.2021_05_05_15_22_10_8029.gpaz.zzz.6aa4ab67-a896-4a98-a141-a87d221d68ff.json
--------+----------+---------+---------+---------
num links:  0 , num pkgs:  0 , num runs:  0

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      0.0                    0.0
ALL MPI               0.0                    0.0
MPI    < 15 mins      0.0                    0.0
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0 
``

**Comment by rtmclay** [comment]
I have updated XALT to version 2.10.5.  In this version I have added tracking of what the xalt_file_to_db.py command is doing.  Here is what I see when I try to load a link and a run *.json file:
```

/home/.../.xalt.d/link.jedrik.example.json
  --> Trying to load json
  --> Sending record to xalt.link_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for build_uuid in db
  --> Trying to insert link record into db
  --> Success: link recorded
  --> Trying to insert objects into db
  --> Trying to insert functions into db
  --> Done

/home/.../.xalt.d/run.jedrik.example.json
  --> Trying to load json
  --> Checking CRC
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Success: stored full xalt_run record
  --> Trying to insert objects into db
  --> Trying to insert env vars into db
  --> Done
```

Please test XALT 2.10.5 to see if this version will help track down where the issue is.

**Comment by gcpmendez** [comment]
Here is the output:

```bash
[root@node2206-3 sbin]# ./xalt_file_to_db.py -D --confFn /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf 

################################################################
XALT Git Version: xalt-2.10.5
  Using XALT_FILE_PREFIX: "USE_HOME"
################################################################

/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.aaa.44f598d4-c881-432d-8000-0daa4a53de7d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.zzz.44f598d4-c881-432d-8000-0daa4a53de7d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.aaa.72d7980c-0dac-494c-8217-9a3b2f27804d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.zzz.72d7980c-0dac-494c-8217-9a3b2f27804d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.aaa.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.zzz.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.aaa.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.zzz.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.aaa.5e73d269-77a1-4603-9874-f209a20f4d99.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.zzz.5e73d269-77a1-4603-9874-f209a20f4d99.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.aaa.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.zzz.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_41_16_3548.root.aaa.e909e66d-f7e1-459f-8758-850c52dfc05e.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_41_16_3548.root.zzz.e909e66d-f7e1-459f-8758-850c52dfc05e.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
--/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.aaa.44f598d4-c881-432d-8000-0daa4a53de7d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_22_39_1768.root.zzz.44f598d4-c881-432d-8000-0daa4a53de7d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.aaa.72d7980c-0dac-494c-8217-9a3b2f27804d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_13_9719.root.zzz.72d7980c-0dac-494c-8217-9a3b2f27804d.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.aaa.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_41_6632.root.zzz.c39b414f-22bb-4bf0-ab7d-431c1099ceaf.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.aaa.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_23_55_0585.root.zzz.5f3467f3-07c2-46b4-89d4-6733d4ed06f8.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.aaa.5e73d269-77a1-4603-9874-f209a20f4d99.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_24_04_5929.root.zzz.5e73d269-77a1-4603-9874-f209a20f4d99.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.aaa.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_33_57_2130.root.zzz.33658ae1-584c-4fe8-a701-1f7139f65b9a.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_41_16_3548.root.aaa.e909e66d-f7e1-459f-8758-850c52dfc05e.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_05_15_41_16_3548.root.zzz.e909e66d-f7e1-459f-8758-850c52dfc05e.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
------+---------+---------+---------+---------|-/home/gpaz/.xalt.d/run.teidehpc.2021_05_05_15_22_10_8029.gpaz.aaa.6aa4ab67-a896-4a98-a141-a87d221d68ff.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
/home/gpaz/.xalt.d/run.teidehpc.2021_05_05_15_22_10_8029.gpaz.zzz.6aa4ab67-a896-4a98-a141-a87d221d68ff.json
  --> Trying to load json
  --> Checking CRC
  --> failed to record: CRC did not match
--------+---------+---------+---------+---------
num links:  0 , num pkgs:  0 , num runs:  0

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      0.0                    0.0
ALL MPI               0.0                    0.0
MPI    < 15 mins      0.0                    0.0
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0 

```

**Comment by rtmclay** [comment]
Thanks for sending that.  I think that the problem is Unicode conversion issues.  What are values do you have for the following environment variables?

    LANG
    LANGUAGE
    LC_COLLATE

**Comment by gcpmendez** [comment]
thank u for ur support 

LANG = en_US.UTF-8
LANGUAGE = 
LC_COLLATE =

**Comment by rtmclay** [comment]
I am assuming that root's LANG is also en_US.UTF-8.  It is also possible that python is using something different to control the Unicode translation.  But first please test out XALT 2.10.6  This version will report the CRC values if they are different. 

The surprising thing is that I get matching CRC values with your example.json file.  So I'm not sure what is the issue with the CRC calculation.

**Comment by gcpmendez** [comment]
I have obtained this output:

`[root@node2206-3 sbin]# ./xalt_file_to_db.py -D --confFn /opt/envhpc/xalt/xalt/sbin/xalt_db_db.conf 

################################################################
XALT Git Version: xalt-2.10.6
  Using XALT_FILE_PREFIX: "USE_HOME"
################################################################

/root/.xalt.d/run.teidehpc.2021_05_06_09_03_48_7275.root.aaa.a0a2db6e-2bb5-4075-b745-5b7b05fd73f9.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x5a05  computed crc: -0x512da5fb
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_03_48_7275.root.zzz.a0a2db6e-2bb5-4075-b745-5b7b05fd73f9.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x2f30  computed crc: 0x744e2f30
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_06_44_3989.root.aaa.fc319516-d34d-4e4a-8333-fa8552fda39f.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x8524  computed crc: -0x7c2c7adc
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_06_44_3989.root.zzz.fc319516-d34d-4e4a-8333-fa8552fda39f.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xdacf  computed crc: -0x41af2531
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_12_00_6039.root.aaa.7b37e903-38ea-4bd6-a223-d35002efbe06.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x58dc  computed crc: -0x7edba724
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_12_00_6039.root.zzz.7b37e903-38ea-4bd6-a223-d35002efbe06.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xbcf8  computed crc: 0x3a8abcf8
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_20_59_7140.root.aaa.d668fd2a-a615-45cd-98b1-64d7ac3a3427.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xca88  computed crc: 0x45fdca88
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_20_59_7140.root.zzz.d668fd2a-a615-45cd-98b1-64d7ac3a3427.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x7c16  computed crc: -0x485983ea
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_21_22_4071.root.aaa.b6ef875f-4360-4b86-8d3f-1423ae2868a3.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x50c9  computed crc: 0x79a50c9
  --> failed to record: CRC did not match
---/root/.xalt.d/run.teidehpc.2021_05_06_09_03_48_7275.root.aaa.a0a2db6e-2bb5-4075-b745-5b7b05fd73f9.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x5a05  computed crc: -0x512da5fb
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_03_48_7275.root.zzz.a0a2db6e-2bb5-4075-b745-5b7b05fd73f9.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x2f30  computed crc: 0x744e2f30
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_06_44_3989.root.aaa.fc319516-d34d-4e4a-8333-fa8552fda39f.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x8524  computed crc: -0x7c2c7adc
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_06_44_3989.root.zzz.fc319516-d34d-4e4a-8333-fa8552fda39f.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xdacf  computed crc: -0x41af2531
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_12_00_6039.root.aaa.7b37e903-38ea-4bd6-a223-d35002efbe06.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x58dc  computed crc: -0x7edba724
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_06_09_12_00_6039.root.zzz.7b37e903-38ea-4bd6-a223-d35002efbe06.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xbcf8  computed crc: 0x3a8abcf8
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_20_59_7140.root.aaa.d668fd2a-a615-45cd-98b1-64d7ac3a3427.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xca88  computed crc: 0x45fdca88
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_20_59_7140.root.zzz.d668fd2a-a615-45cd-98b1-64d7ac3a3427.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x7c16  computed crc: -0x485983ea
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_09_21_22_4071.root.aaa.b6ef875f-4360-4b86-8d3f-1423ae2868a3.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x50c9  computed crc: 0x79a50c9
  --> failed to record: CRC did not match
------+---------+----------+---------+----------|---------+----------+---------+----------+---------
num links:  0 , num pkgs:  0 , num runs:  0

Kind                Count    Average Time (secs)
----                -----    -------------------
Scalar < 15 mins      0.0                    0.0
Scalar < 30 mins      0.0                    0.0
Scalar < 60 mins      0.0                    0.0
Scalar > 60 mins      0.0                    0.0
ALL MPI               0.0                    0.0
MPI    < 15 mins      0.0                    0.0
MPI    < 30 mins      0.0                    0.0
MPI    < 60 mins      0.0                    0.0
MPI    > 60 mins      0.0                    0.0 
`



with the  "$ make install" I have obtained this:

```bash
make[1]: Entering directory `/opt/envhpc/xalt/src'
makefile:95: linker/jsmn.d: No such file or directory
makefile:95: linker/my_uuidgen.d: No such file or directory
makefile:95: linker/xalt_realpath.d: No such file or directory
makefile:95: util/buildJson.d: No such file or directory
makefile:95: util/buildXALTRecordT.d: No such file or directory
makefile:95: util/build_uuid.d: No such file or directory
makefile:95: util/capture.d: No such file or directory
makefile:95: util/compute_sha1.d: No such file or directory
makefile:95: util/crcFast.d: No such file or directory
makefile:95: util/epoch.d: No such file or directory
makefile:95: util/extractMain.d: No such file or directory
makefile:95: util/insert.d: No such file or directory
makefile:95: util/process.d: No such file or directory
makefile:95: util/transmit.d: No such file or directory
makefile:95: util/xalt_c_utils.d: No such file or directory
makefile:95: util/xalt_curl_transmit.d: No such file or directory
makefile:95: util/xalt_dir.d: No such file or directory
makefile:95: util/xalt_epoch.d: No such file or directory
makefile:95: util/xalt_fgets_alloc.d: No such file or directory
makefile:95: util/xalt_quotestring.d: No such file or directory
makefile:95: util/xalt_record_pkg.d: No such file or directory
makefile:95: util/xalt_tmpdir.d: No such file or directory
makefile:95: util/xalt_vendor_note.d: No such file or directory
makefile:95: libxalt/buildEnvT.d: No such file or directory
makefile:95: libxalt/buildUserT.d: No such file or directory
makefile:95: libxalt/parseProcMaps.d: No such file or directory
makefile:95: libxalt/run_submission.d: No such file or directory
makefile:95: libxalt/translate.d: No such file or directory
makefile:95: libxalt/walkProcessTree.d: No such file or directory
makefile:95: libxalt/xalt_initialize.d: No such file or directory
makefile:95: libxalt/xalt_test.d: No such file or directory
makefile:95: linker/buildRmapT.d: No such file or directory
makefile:95: linker/parseJsonStr.d: No such file or directory
makefile:95: linker/parseLDTrace.d: No such file or directory
makefile:95: linker/xalt_extract_linker.d: No such file or directory
makefile:95: linker/xalt_generate_linkdata.d: No such file or directory
makefile:95: linker/xalt_generate_watermark.d: No such file or directory
makefile:95: linker/xalt_rmap_exists.d: No such file or directory
makefile:95: linker/xalt_strip_linklib.d: No such file or directory
makefile:95: linker/xalt_utils.d: No such file or directory
makefile:95: util/test_record_pkg.d: No such file or directory
makefile:95: util/xalt_configuration_report.d: No such file or directory
make[1]: Leaving directory `/opt/envhpc/xalt/src'
```

**Comment by gcpmendez** [comment]
Removing module python/3.7.4 I didn't obtain the errors:

```bash
make[1]: Entering directory `/opt/envhpc/xalt/src'
make[1]: Leaving directory `/opt/envhpc/xalt/src'
make[1]: Entering directory `/opt/envhpc/xalt/src'
XALT_EXECUTABLE_TRACKING: ''
```

**Comment by gcpmendez** [comment]
Seems the last number matching ..

```bash
/root/.xalt.d/run.teidehpc.2021_05_07_10_02_23_6886.root.zzz.1b9dbd57-64ec-4134-b001-8d1b0922c173.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0xf232  computed crc: 0x2408f232
  --> failed to record: CRC did not match
/root/.xalt.d/run.teidehpc.2021_05_07_10_04_36_8049.root.aaa.e0537b07-fe27-475d-bacb-78d8828d35b6.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> crcStr: 0x298d  computed crc: 0x652298d
  --> failed to record: CRC did not match
```

**Comment by rtmclay** [comment]
Thanks for testing with multiple pythons!  Please test the latest version (XALT-2.10.8) to see if it works better with both pythons.

**Comment by gcpmendez** [comment]
Now it works! 
Thank you ;)
