### ISSUE TITLE
Problem uploading json to database

### ISSUE THREAD

**Issue by gcpmendez** [xalt/xalt#46]
When I ran a job in slurm with job_id 895565 and after that I ran xalt_file_to_db.py I got see the register but when I again ran the same job in slurm with another job_id and after that I execute xalt_file_to_db.py I didn't get see the register.

![imagen](https://user-images.githubusercontent.com/10725162/118126186-e5451e80-b3ef-11eb-8497-b008127ea873.png)

In the json file I get see the register to insert it:
![imagen](https://user-images.githubusercontent.com/10725162/118126229-f8f08500-b3ef-11eb-97fd-6121d2de54d1.png)

And the database updated the end_time with the first register:
![imagen](https://user-images.githubusercontent.com/10725162/118126331-17ef1700-b3f0-11eb-8b5e-aceefe6c52c5.png)

**Comment by rtmclay** [comment]
XALT creates a UUID, (called here the run_uuid) to uniquely store each execution in the database. Your executions are getting the same run_uuid: deadbeaf-dead-beef-1111-deadbeef1111.  That only happens when XALT cannot find the libuuid.so library.  XALT writes to stderr when it can't find libuuid.so.  You should see the error in your job output.

You might want to run interactively on a compute node  with a simple program that prints a message.  Please follow the steps described here: 

https://xalt.readthedocs.io/en/latest/090_testing_xalt.html?highlight=debug#step-6-run-a-program-with-xalt-tracing-turned-on

You should also make sure that a copy of libuuid.so is in the installed directory for XALT's lib64 directory.  In TACC's case we install XALT in /opt/apps/xalt/xalt.  So in the /opt/apps/xalt/xalt/lib64 directory we have:

```
% ls -l libuuid.so*
lrwxrwxrwx 1 root install    16 Mar  2 09:56 libuuid.so -> libuuid.so.1.3.0
lrwxrwxrwx 1 root install    16 Mar  2 09:56 libuuid.so.1 -> libuuid.so.1.3.0
-rwxr-xr-x 1 root install 20112 Mar  1 18:36 libuuid.so.1.3.0
```

Please make sure that you as a user have the correct permissions.

**Comment by gcpmendez** [comment]
I ran $ yum install libuuid libuuid-devel before $ configure and $make install and now I don't find such libraries in that path.

Any solution?

**Comment by rtmclay** [comment]
Configure and make are supposed to copy libuuid.so to XALT's lib64 directory.  You will have to look at the output of make to see what happened.  Look for "copy_system_library_to_xalt.py" and see what went wrong.

**Comment by gcpmendez** [comment]
I saw the next:
```
          /opt/envhpc/xalt/proj_mgmt/py_build_tools/copy_system_library_to_xalt.py --lib64 /opt/envhpc/xalt/2.10.8/lib64              \
                               --base $baseNM                         \
                               --real $realNM;                        \
        done
Cannot deal w/link:  ../../lib64/libuuid.so.1.3.0

```
Also I attach u both logs:
[log_configure.txt](https://github.com/xalt/xalt/files/6473104/log_configure.txt)
[log_install.txt](https://github.com/xalt/xalt/files/6473102/log_install.txt)

**Comment by rtmclay** [comment]
Thanks for the log files.  They were helpful in tracking down the problem where libuuid.so was not copied to the XALT lib64 install directory. I have been able to reproduce your error and fix it.  I have uploaded to github XALT-2.10.9.  Please test this version to see if it works correctly for you.  Namely that the libuuid.so library is copied to the XALT lib64 directory.

Thanks very much for the bug report!

**Comment by gcpmendez** [comment]
I attach u new logs:
[log_configure.txt](https://github.com/xalt/xalt/files/6477434/log_configure.txt)
[log_install.txt](https://github.com/xalt/xalt/files/6477435/log_install.txt)

the problem wasn't solved

**Comment by rtmclay** [comment]
O.K.  

(1) Please run the following commands and send me the results:

```
$ cd /usr/lib64; ls -l libuuid.so*
$ cd /lib64;   ls -l libuuid.so*
```

The copy_system_library_to_xalt.py needs to follow the links for libuuid.so.  

(2) What Operating System are you installing XALT on?

**Comment by gcpmendez** [comment]
![imagen](https://user-images.githubusercontent.com/10725162/118268102-dbd1ba00-b4b4-11eb-88b5-34fc1ef1f2e3.png)

**Comment by rtmclay** [comment]
Thanks for that information.  I was able to test your case and track the problem down.  Please try XALT-2.10.10 to see if it fixes your problem.

**Comment by gcpmendez** [comment]
fixed! .. thank u ))

**Comment by gcpmendez** [comment]
In the new version I obtained this when I ran xalt_configuration_report

[gpaz@node2206-3 ~]$ xalt_configuration_report 
dirname: extra operand `/bin/bash'
Try `dirname --help' for more information.
/opt/envhpc/xalt/2.10.10/bin/xalt_configuration_report: line 5: /usr/bin/dirname/../libexec/xalt_configuration_report.x: Not a directory

**Comment by rtmclay** [comment]
What is the contents of the script ```xalt_configuration_report```?   Does xalt_configuration_report.x exist in the libexec directory?

**Comment by gcpmendez** [comment]
![imagen](https://user-images.githubusercontent.com/10725162/118650709-a7c00700-b7dc-11eb-84d8-fa0b71dbfb51.png)

**Comment by rtmclay** [comment]
Please try each of the steps in the script. So for example:
```
LOC=$(PATH=/usr/bin:/bin:/usr/local/bin readlink -f /opt/envhpc/xalt/xalt/bin/xalt_configuration_report); echo $LOC
MY_DIR=$(PATH=/usr/bin:/bin:/usr/local/bin dirname $LOC); echo $MY_DIR
```

Does executing ```/opt/envhpc/xalt/xalt/libexec/xalt_configuration_report.x``` work?

**Comment by gcpmendez** [comment]
![imagen](https://user-images.githubusercontent.com/10725162/118653891-e60af580-b7df-11eb-88a4-b3d461dc24d6.png)

**Comment by rtmclay** [comment]
For some reason the readlink command or the dirname command is not working and I need your help to understand why it is not working for you.  Here is a modified version of xalt_configuration_report:

```
#!/bin/bash
# -*- shell -*-

LOC=$(PATH=/usr/bin:/bin:/usr/local/bin readlink -f $0); echo LOC=$LOC
MY_DIR=$(PATH=/usr/bin:/bin dirname $LOC); echo MY_DIR=$MY_DIR
LD_LIBRARY_PATH=/opt/apps/xalt/xalt/lib64 $MY_DIR/../libexec/xalt_configuration_report.x "$@"
```

Please replace your installed xalt_configuration_report with the one above and run it.

And here is what I get when I run this command:
```
$ XALT_EXECUTABLE_TRACKING=yes /opt/apps/xalt/xalt/bin/xalt_configuration_report
LOC=/opt/apps/xalt/2.10.10/bin/xalt_configuration_report
MY_DIR=/opt/apps/xalt/2.10.10/bin
*------------------------------------------------------------------------------*
                      XALT Configuration Report
*------------------------------------------------------------------------------*
```

So what happens when you run:
```
$ type -a readlink
$ type -a dirname
```

It seems that the readlink or dirname are not the ones that I'm expecting run and I need your help to track down why.

**Comment by gcpmendez** [comment]
![imagen](https://user-images.githubusercontent.com/10725162/118657396-5b2bfa00-b7e3-11eb-891f-c798e3953ad4.png)

**Comment by rtmclay** [comment]
There is something that is not part of XALT that is failing on your system.  Do you see that this is strange?  Why is /bin/bash appearing?  What happens if you do:
```
$ /bin/readlink -f /opt/envhpc/xalt/xalt/bin/xalt_configuration_report
``` 
These commands are normal Unix commands.  Do you have some special bash shell option turned on?

**Comment by gcpmendez** [comment]
The problem is the line `['KEEP',  r'.*']` in the file /opt/envhpc/xalt/src/tmpl/xalt_config.py.
If I delete this line the error happens.

But I don't want keep path_patterns for all.

**Comment by rtmclay** [comment]
You can add the following to your config.py file after your KEEP line for /opt/*:
```
  ['SKIP',  r'.*']
```

That will override the last line in xalt_config.py

I will test that configuration on my system.  I assume that the ```xalt_configuration_report``` works on your login nodes.

**Comment by rtmclay** [comment]
I have tested this configuration and I don't reproduce the issue you see:

```
*----------------------*
 Array: pathPatternA
*----------------------*
   0: KEEP => ^\/opt\/.*
================== src/tmpl/xalt_config.py ==================
   1: SKIP => ^\/home1\/00515\/mclay\/l\/pkg\/xalt\/xalt\/.*
   2: SKIP => .*\/bin\/my_uuidgen
   3: SKIP => .*\/logger
   4: SKIP => .*\/xalt_print_os
   5: SKIP => .*\/xalt_syslog_to_db
   6: SKIP => .*\/xalt_extract_record.x
   7: SKIP => .*\/xalt_configuration_report.x
   8: SKIP => .*\/xalt_syshost
   9: SKIP => .*\/xalt_record_pkg
  10: KEEP => .*
```

**Comment by rtmclay** [comment]
I have been thinking about the results you got trying to run xalt_configuration_report.  I am concerned that you are getting some output to either stdout or stderr from running XALT.  I am interested in knowing what the output of the following is:
```
$ /bin/readlink -f /opt/envhpc/xalt/xalt/bin/xalt_configuration_report 2> err.out > std.out
```

I would like to know what is in err.out and std.out.

If you get anything in err.out, please try:

```
$ XALT_TRACING=yes XALT_SAMPLING=no /bin/readlink -f /opt/envhpc/xalt/xalt/bin/xalt_configuration_report 2> err.out > std.out
```

and let me know what err.out and std.out have in them.  Please do all this testing with your pathPatternA like I showed in the previous message.

**Comment by gcpmendez** [comment]
I updated to the last version 

![image](https://user-images.githubusercontent.com/10725162/120646774-c297aa00-c471-11eb-86ca-cab45a30ea58.png)

**Comment by gcpmendez** [comment]
Again with the new version 2.10.13 I can't upload the data:
![image](https://user-images.githubusercontent.com/10725162/121029484-867d8580-c7a0-11eb-99a8-eb34d159b8e5.png)

**Comment by rtmclay** [comment]
Please send me a run*.json file.

Thanks!

**Comment by rtmclay** [comment]
Please also look to see that you are generating run*.json files by testing as described here:

https://xalt.readthedocs.io/en/latest/090_testing_xalt.html#step-6-run-a-program-with-xalt-tracing-turned-on

**Comment by gcpmendez** [comment]
[run.teidehpc.2021_06_07_15_08_57_4523.gpaz.aaa.001166a7-8ea0-4daa-a1ec-d16650b7e935.json.txt](https://github.com/xalt/xalt/files/6614084/run.teidehpc.2021_06_07_15_08_57_4523.gpaz.aaa.001166a7-8ea0-4daa-a1ec-d16650b7e935.json.txt)

**Comment by rtmclay** [comment]
I was able to ingest the run*.json file you sent.  I have created a new version of xalt that reports the number of json files xalt_file_to_db.py will ingest.  Please also send me the output of xalt_configuration_report.  The run*.json file you sent me was a run of xalt_configuration_report.  However, this executable is a serial (non-mpi) program and you generated a start record.  That shouldn't happen.  Serial program should only generate an end record.  So I am asking for the following:

1. Please test xalt-2.10.14 and send me the output from running xalt_file_to_db.py
2. Send me the output of xalt_configuration_report
3. Please follow the step outlined here: https://xalt.readthedocs.io/en/latest/090_testing_xalt.html#step-6-run-a-program-with-xalt-tracing-turned-on and send me the output from that.

**Comment by rtmclay** [comment]
I have added some more debugging statement to xalt_file_to_db.py.  Please test xalt-2.10.15 instead. Thanks!

**Comment by gcpmendez** [comment]
From version 2.10.15 the db configuration created with ./conf_create.py isn't neccesary because ./xalt_file_to_db.py ask me every time:
![imagen](https://user-images.githubusercontent.com/10725162/121549574-e3c64080-ca05-11eb-899e-6f291555dc59.png)

xalt_configuration_report output:
[xalt_configuration_report.txt](https://github.com/xalt/xalt/files/6632502/xalt_configuration_report.txt)

**Comment by rtmclay** [comment]
Please read here: https://xalt.readthedocs.io/en/latest/070_loading_json_by_file.html?highlight=confFn#create-script-to-load-json-records-into-the-database to see how to not have to type in the database information each time.

I see from the file xalt_configuratoin_report.txt that you have configured XALT to use /root/.xalt. as the location for ALL results with the --with-xaltFilePrefix=/root/.xalt. 

That is probably not a good location. The file prefix location has to be a location that you have run the create_xalt_directories.sh command.  Also it has to be writable to all users.  It is unlikely that you want all users to be writing to /root/.xalt.  Also that directory has to be the same directory for all nodes. 

It is helpful to respond to all the questions I asked. It is not clear where the json files were being written too.  That would have been answered by doing like I asked you before.

Please follow the step outlined here: https://xalt.readthedocs.io/en/latest/090_testing_xalt.html#step-6-run-a-program-with-xalt-tracing-turned-on and send me the output from that.

Also the installed version of XALT that writes to the database has to be the same as the version of XALT that users run.

From the file run.teidehpc.2021_06_07_15_08_57_4523.gpaz.aaa.001166a7-8ea0-4daa-a1ec-d16650b7e935.json.txt. It clear that this file was written to your home directory (say /home/gpaz/.xalt.d) where as far as XALT-2.10.15 is concerned it expects to find all *.json file under /root/.xalt./...

To fix this please do the following:

1. Pick a global location that is the same shared location on all compute nodes.  For the following discussion I am going to assume that this is */global/xalt/*  Please change */global/xalt* to what works on your system.
2. configure xalt with --with-transmission=file --with-xaltFilePrefix=*/global/xalt*
3. Run the program create_xalt_directories.sh to create the structure necessary in sub-directories below */global/xalt*
4. Install XALT on the compute nodes with the same configuration as step 1
5. Run a simple program on the compute nodes (say hello) as follows:

    $ XALT_TRACING=yes XALT_SAMPLING=no ./hello

6. Make sure that the output from the above program shows that it writes a run*.json file to */global/xalt* or where ever you have chosen to be the global shared location.  Note that for testing with just one user (namely you)  that this global shared location  can be in your home directory.

**Comment by gcpmendez** [comment]
![imagen](https://user-images.githubusercontent.com/10725162/121677242-85ed3380-caad-11eb-941f-42073b15b09a.png)

Last steps followed by me:
```` bash
- Configure and make:
  $ module load tcl/8.6.8/gcc lmod/8.4/gcc lua/5.4.1.9/gcc gcc/6.1.0 python/3.7.4
  $ cd /opt/envhpc/xalt/
  $ cp ../xalt_backup_10_06_2021/Config/TACC_config.py Config/
  $ cp ../xalt_backup_10_06_2021/src/tmpl/xalt_config.py src/tmpl/
  $ ./configure
        --prefix=/opt/envhpc/ 
        --with-syshostConfig=hardcode:teidehpc 
        --with-trackGPU=no 
        --with-MySQL=yes 
        --with-config=Config/TACC_config.py  
        --with-systemPath=/usr/bin:/bin:/usr/local/bin 
        --with-transmission=file  
        --with-cxxLDLibraryPath=/opt/envhpc/gcc/6.1.0/lib64 
        --with-etcDir=/opt/envhpc/xalt/etc/

$ update_lmod_system_cache_files  -d /opt/envhpc/xalt/etc/ -t /tmp/system.txt -R /opt/envhpc/xalt/etc/reverseMapD/xalt_rmapT.json -J -K /opt/envhpc/modulefiles
$ make install
````

TACC_config.py:
[TACC_config.py.txt](https://github.com/xalt/xalt/files/6637932/TACC_config.py.txt)

xalt_config.py:
[xalt_config.py.txt](https://github.com/xalt/xalt/files/6637946/xalt_config.py.txt)

Modulefile:
![imagen](https://user-images.githubusercontent.com/10725162/121678234-d9ac4c80-caae-11eb-8eca-b4695f8c626a.png)

Xalt_configuration_report.txt
[xalt_configuration_report.txt](https://github.com/xalt/xalt/files/6637977/xalt_configuration_report.txt)

I want a json to be created when a user loads a module. Any solution?

**Comment by gcpmendez** [comment]
Ok .. I just see this problem activating XALT_TRACING=yes:
![imagen](https://user-images.githubusercontent.com/10725162/121680455-7d96f780-cab1-11eb-9cb8-dc44af6c20ff.png)

I'll try upload the json files ..

**Comment by gcpmendez** [comment]
I added the next to path_pattherns:
```` bash
path_patterns = [
    ['KEEP',  r'^\/usr\/local\/Modules\/3.2.10\/bin\/modulecmd'],
  ]
````

And now I obtained two json files:
[run.teidehpc.2021_06_11_12_43_26_3839.gpaz.zzz.83e7527c-687c-4ca6-9ae7-ded42deea52f.json.txt](https://github.com/xalt/xalt/files/6638107/run.teidehpc.2021_06_11_12_43_26_3839.gpaz.zzz.83e7527c-687c-4ca6-9ae7-ded42deea52f.json.txt)
[run.teidehpc.2021_06_11_12_43_26_3839.gpaz.aaa.83e7527c-687c-4ca6-9ae7-ded42deea52f.json.txt](https://github.com/xalt/xalt/files/6638108/run.teidehpc.2021_06_11_12_43_26_3839.gpaz.aaa.83e7527c-687c-4ca6-9ae7-ded42deea52f.json.txt)

and upload not works:
![imagen](https://user-images.githubusercontent.com/10725162/121682200-af10c280-cab3-11eb-887e-7efec89c6a53.png)

**Comment by rtmclay** [comment]
You asked about creating a json file when a user runs the module command.  If you are interested in knowing what modules are loaded by users why not get the module system to do that.  Lmod can easily be setup to do that. It appears that you are using Tmod  3.2.10.  Lmod can read and evaluate TCL modulefiles.  You might consider using Lmod instead of Tmod 3.2.10.  It might be possible to get Tmod 4 to track modules.  You could check the environmental module documentation or the modules  mailing list.

I see that you have generated json files from XALT-2.10.15 and xalt_file_to_db.py  are writing results to ~/.xalt.d.  That is good. 
What I can't tell is where the xalt_file_to_db.py ended.  It should report the number of json files to process right after it prints the version and the value of XALT_FILE_PREFIX.  What happened next? Did the program quit?

No you don't need to regenerate the database.  As far as I can tell, you are not finding *.json files to ingest.

Here is what happens when I ingest two json files:
```
################################################################
XALT Git Version: xalt-2.10.15-1-g604bcb6
  Using XALT_FILE_PREFIX: "USE_HOME"
  Number of json files to process: 2
################################################################


################################################################
 Note using ~/.xalt.d to store result is fine for testing.
 BUT do not use in production. There is a race condition
 Please re-configure xalt to use --with-xaltFilePrefix=...
 See https://xalt.readthedocs.io/en/latest/020_site_configuration.html for details

 Add the option --testing to silence this warning
################################################################

/home/mclay/w/xalt/rt/end2end/t1/x86_64_06_avx2_dbg_gcc-9.3.0_mpich-3.3.2-2021_06_10_16_44_23-Linux-x86_64-end2end/.xalt.d/link/link.jedrik.example.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> Sending record to xalt.link_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for build_uuid in db
  --> Trying to insert link record into db
  --> Success: link recorded
  --> Trying to insert objects into db
  --> Trying to insert functions into db
  --> Done

+/home/mclay/w/xalt/rt/end2end/t1/x86_64_06_avx2_dbg_gcc-9.3.0_mpich-3.3.2-2021_06_10_16_44_23-Linux-x86_64-end2end/.xalt.d/run/run.jedrik.example.json
  --> Trying to open file
  --> Trying to load json
  --> Checking CRC
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Success: stored full xalt_run record
  --> Trying to insert objects into db
  --> Trying to insert env vars into db
  --> Done

Storing the following 2 json files (run: 1, link: 1, pkg: 0) for user mclay
```

Does this help?

**Comment by gcpmendez** [comment]
What happened next? Did the program quit? ..
The executable got stuck and did not continue

**Comment by rtmclay** [comment]
That make sense.  I changed XALT-2.10.15 to count the number of *.json files before ingesting.  On my personal computer, that is quick but it might fast not be on a cluster.  I have now removed that "feature" and released xalt-2.10.16.  Please install xalt-2.10.16 and try ingesting the *.json files in the ~/.xalt.d directories.

**Comment by gcpmendez** [comment]
New error uploading the json files:
![imagen](https://user-images.githubusercontent.com/10725162/121913719-8a258500-cd29-11eb-8669-f8221369bb7b.png)

**Comment by rtmclay** [comment]
Please send me the *.json files that can reproduce this error.  You can try restarting the database.  But I do not think that this is the problem.

**Comment by gcpmendez** [comment]
[run.teidehpc.2021_06_11_08_19_00_1412.root.aaa.25a1f1e7-b153-401c-9631-2fe392885901.json.txt](https://github.com/xalt/xalt/files/6654000/run.teidehpc.2021_06_11_08_19_00_1412.root.aaa.25a1f1e7-b153-401c-9631-2fe392885901.json.txt)

**Comment by rtmclay** [comment]
Thanks for sending me the *.json file.  I was able to reproduce the issue you found and fix it for me.  Please test xalt-2.10.18 to see if it works for you. 

The issue was that when I added all the debugging tracking statements that I failed to handle a previous error tracking tool I added much earlier. This is now fixed.

**Comment by gcpmendez** [comment]
New stuck ..
![imagen](https://user-images.githubusercontent.com/10725162/122201950-777b8f00-ce94-11eb-97f2-5fcaef5fcd06.png)
[run.teidehpc.2021_06_08_08_43_19_9266.jfelipe.zzz.5c81d11b-43f9-47c4-b60b-a798d11afe39.json.txt](https://github.com/xalt/xalt/files/6662157/run.teidehpc.2021_06_08_08_43_19_9266.jfelipe.zzz.5c81d11b-43f9-47c4-b60b-a798d11afe39.json.txt)

**Comment by rtmclay** [comment]
In order for me to test it completely, I need the start record.  Could you send me:

run.teidehpc.2021_06_08_08_43_19_9266.jfelipe.aaa.5c81d11b-43f9-47c4-b60b-a798d11afe39.json.txt

**Comment by rtmclay** [comment]
Please do send me the start record that I asked for above, I'll want to check that it gets correctly ingested into the database.

However, I am pretty sure that the issue relates to using configuring XALT to use --with-transmission=file without --with-xaltFilePrefix=...

I believe that the program ```xalt_file_to_db.py``` is working correctly, if a little slow.

The issue is that parallel file systems are slow to walk.  When you are running xalt_file_to_db.py as you have configured now, you are walking over the entire list of user in /etc/passwd and looking for *.json files in each users ~/.xalt.d directory.

I have modified xalt_file_to_db.py to print the user's directory that it searching.  If you run xalt_file_to_db.py you'll see it slowly printing out each username.

You should reconfigure and install XALT using both --with-transmission=file and --with-xaltFilePrefix=/global/xalt/...
where /global/xalt is some directory that is shared across all login and compute nodes.  Make sure to run the script create_xalt_directories.sh to correctly setup /global/xalt (or whatever you use).  

Also you should use 
```XALT_TRACING=yes XALT_SAMPLING=no hello```
to make sure that xalt writes the *.json file to the correct location.  Here is example from my testing suite that writes to a shared location.  In my case I have configured XALT to write to /global/xalt/DATA

```
myfini(0/1,LD_PRELOAD,/home/user/hello){
    -> XALT_SAMPLING = "no" All programs tracked!
  Recording State at end of scalar user program

  run_submission(.zzz) {
    Built processTree table
    Built envT
    Extracted recordT from watermark
    Built userT, userDT, scheduler: SLURM
    Compute sha1 (c506c09fb8ce986db136e1f854337a2409945333) of exec: /home/user/hello
    Parsed ProcMaps
    Using XALT_TRANSMISSION_STYLE: file
    Built json string
    Transmitting jsonStr
    Wrote json run file : /global/xalt/DATA/run/08/run.jedrik.2021_06_16_18_38_46_5704.mclay.zzz.5acd94e9-ad7a-4fd1-8291-62be2c5ec134.json
    Done transmitting jsonStr
  }

    -> leaving myfini
}
```
The important line above is where it wrote the *.json file.

**Comment by gcpmendez** [comment]
I like this configuration by the moment ..

With new version 2.10.19 I got a new stuck ..
![imagen](https://user-images.githubusercontent.com/10725162/122398892-3ce82400-cf72-11eb-82f0-b7b1e8c3f31d.png)
...
![imagen](https://user-images.githubusercontent.com/10725162/122398979-4f625d80-cf72-11eb-8e27-1b8eba37c066.png)

**Comment by rtmclay** [comment]
I have updated XALT to have more debugging print statements to follow what is happening.  Please test XALT-2.10.20 and let me know what happens when you test with the -D option to xalt_file_to_db.py

Here is that happens when I test it:

```
$ xalt_file_to_db.py -D --testing --confFn testxalt_db.conf --reverseMapD ./reverseMapD

Searching for *.json files for mclay in /home/user/.xalt.d/
Searching for */link.*.json file in /home/user/.xalt.d/
  --> Found 1 link.*.json files

/home/user/.xalt.d/link/link.jedrik.example.json
  --> Trying to open file
  --> Trying to load json
  --> Sending record to xalt.link_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for build_uuid in db
  --> Trying to insert link record into db
  --> Success: link recorded
  --> Trying to insert objects into db
  --> Trying to insert functions into db
  --> Done

Searching for */run.*.json file in /home/user/.xalt.d
  --> Found 4 run.*.json files

/home/user/.xalt.d/run/run.jedrik.example.json
  --> Trying to open file
  --> Trying to load json
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Success: stored full xalt_run record
  --> Trying to insert objects into db
  --> Trying to insert env vars into db
  --> Done

/home/user/.xalt.d/run/run.jedrik.example_2.json
  --> Trying to open file
  --> Trying to load json
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Success: stored full xalt_run record
  --> Trying to insert objects into db
  --> Trying to insert env vars into db
  --> Done

/home/user/.xalt.d/run/run.jedrik.example_3.json
  --> Trying to open file
  --> Trying to load json
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Success: stored full xalt_run record
  --> Trying to insert objects into db
  --> Trying to insert env vars into db
  --> Done

/home/user/.xalt.d/run/run.jedrik.example_dup.json
  --> Trying to open file
  --> Trying to load json
  --> Sending record to xalt.run_to_db()
  --> Trying to connect to database
  --> Starting TRANSACTION
  --> Searching for run_uuid in db
  --> Trying to insert run record into db
  --> Duplicate run_uuid, not recorded --> FAILURE

Storing the following 5 json files (run: 4, link: 1, pkg: 0) for user mclay

num links:  1 , num pkgs:  0 , num runs:  3 , dups:  1

$
```

**Comment by gcpmendez** [comment]
Now its going better
Thank you
