### ISSUE TITLE
Question on libuuid-devel requirement

### ISSUE THREAD

**Issue by JLague** [xalt/xalt#51]
Since xalt looks specifically for `libuuid.so`, it can't generate a uuid for the record if the `libuuid-devel` package is not installed (i.e. there is no symlink `libuuid.so -> libuuid.so.1`).

What is the reason why the `libuuid-devel` package is used instead of just using `libuuid`?

**Comment by rtmclay** [comment]
XALT uses both packages. It needs to find the uuid library in both regular system and containers.  To get it to work the install process installs copies the *.so and the symlinks to the $LIB64 directory.  It does this by using the dlopen and dlsym function to dynamically with the functions from the uuid library.   See src/util/build_uuid.c

**Comment by JLague** [comment]
Ah yes, I see that `src/util/build_uuid.c` needs the `uuid.h` header. Thanks for the explanation!
