### ISSUE TITLE
Increase the default length of the column 'queue'

### ISSUE THREAD

**Issue by ZQyou** [xalt/xalt#57]
We got this error while runing `xalt_syslog_to_db.py`:

```
_mysql_exceptions.DataError: (1406, "Data too long for column 'queue' at row 1")
```

The queue value has 43 characters but the length of the column queue is 32. We have fixed it locally but hope this change can be made in coming release.

**Comment by ZQyou** [comment]
After altering the column size, I still got the oversized error. The queue value this time is

```
'queue': 'parallel-48core,parallel-40core,condo-olivucci-backfill-parallel,gpubackfill-parallel-40core,condo-osumed-gpu-48core-backfill-parallel,gpubackfill-parallel-48core,condo-datta-backfill-parallel,condo-honscheid-backfill-parallel,condo-tarnovsky-olivucci-backfill-parallel,condo-ccapp-backfill-parallel,gpubackfill-parallel-quad,condo-osumed-gpu-quad-backfill-parallel,condo-osumed-gpu-40core-backfill-parallel
```
It contains all our backfill partitions. The actual partition from our SLURM sacct is `parallel-48core`.

**Comment by rtmclay** [comment]
Thanks very much for the bug report.  I have changed length of queue to be 64 chars.  Also I have used your fix and updated it to be:

```
        # Queue name could have a comma list.  Pick 1st one and limit it to 64 chars.
        queue         = userT.get('queue').split(',')[0][:64]
```

This will become live at the next release of XALT.

**Comment by ZQyou** [comment]
Thanks. I see this update in 2.10.37.  

Also I just found that if one does not care about the exact queue name, disabling strict mode in MySQL allows the automatic truncation of the inserted string. This might be a workaround if one does not upgrade to 2.10.37.
