### ISSUE TITLE
"Less" fails to preload on SUSE os

### ISSUE THREAD

**Issue by benfulton** [xalt/xalt#58]
Running less on a cluster running SLES15 results in the following error:

`ERROR: ld.so: object '/N/soft/sles15/xalt/2.10.34/lib64/libxalt_init.so' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.`

It appears to be the LESS preprocessor (/usr/bin/lessopen.sh) that's causing this.  If you unset the LESSOPEN variable, the errors stop.
The variable LESSOPEN is set to lessopen.sh %s in SLES (/etc/profile, /etc/csh.login).  That script was the subject of some controversy a few years back, due to the many binaries it calls, temp files it uses, etc: https://bugzilla.suse.com/show_bug.cgi?id=906858

The resolution was to create an AppArmor profile for the script; that profile is preventing the memory modification involved in xalt's LD_PRELOAD behavior.

**Comment by rtmclay** [comment]
XALT is using the hooks into ELF binaries which it looks like SLES is blocking.  There is not much that XALT can do in this case.  My only suggestion is to make the less command somehow set LD_PRELOAD="" for just that command.
