### ISSUE TITLE
mysql_native_password and caching_sha2_password

### ISSUE THREAD

**Issue by KhanradCoder** [xalt/xalt#64]
**Describe the bug**
When trying to connect to a MySQL DB from the `python3 /opt/xalt/xalt/3.0.1/sbin/createDB.py --dbname $DBNAME` command, the following error occurs:
`Error 2059: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory`

**To Reproduce**
For context here is the Dockerfile we are using to build everything:
```
# Use CentOS 7 as the base image
FROM centos:7

# Install necessary dependencies for XALT and Lmod
RUN yum update -y && yum install -y \
    epel-release \
    && yum install -y \
    gcc gcc-c++ \
    git make \
    python3 python3-pip python3-devel \
    lua lua-devel luarocks \
    tcl tcl-devel \
    environment-modules \
    libuuid-devel \
    libcurl-devel \
    openssl-devel \
    elfutils-libelf-devel \
    flex \
    mariadb-server \
    mariadb-devel \
    mysql \
    mysql-server \
    which file findutils \
    && yum clean all

# Install Python MySQL client library
RUN pip3 install mysqlclient

# Install Lmod, a Lua-based environment module system
RUN luarocks install luaposix
RUN git clone https://github.com/TACC/Lmod.git /Lmod \
    && cd /Lmod \
    && ln -s /opt/apps/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh

# Set environment for Lmod
ENV BASH_ENV=/etc/profile.d/z00_lmod.sh \
    ENV=/etc/profile.d/z00_lmod.sh \
    PROMPT_COMMAND=". /etc/profile.d/z00_lmod.sh"

# Clone XALT repository
RUN git clone https://github.com/KhanradCoder/xalt /xalt

# Set working directory to the XALT directory
WORKDIR /xalt
 
# Set the SYSTEM_PATH environment variable to include the paths of required utilities and libraries
ENV SYSTEM_PATH="/usr/bin:/bin:/usr/sbin:/usr/lib64:/opt/xalt/xalt/3.0.1/lib64/"

COPY config.py config.py

# Run the configure script and make commands
RUN ./configure --prefix=/opt/xalt/xalt/3.0.1/ \
    --with-syshostConfig=hardcode:Rivanna \
    --with-transmission=file \
    --with-trackScalarPrgms=no \
    --with-trackGPU=no \
    --with-siteControlledPrefix=yes \
    --with-functionTracking=no \
    --with-systemPath=$SYSTEM_PATH \
    --with-config=config.py \
    && make all install
    
ENV PATH="/opt/xalt/xalt/xalt/bin:${PATH}"
ENV LD_LIBRARY_PATH=/opt/xalt/xalt/3.0.1/lib64:$LD_LIBRARY_PATH
```
 Lmod version is 8.7.37.

**Expected behavior**
Since as of MySQL 8.0 `caching_sha2_password` is now the default authentication plugin rather than `mysql_native_password`, what is the best workaround for connecting XALT to a MySQL 8.0+ database?

**Desktop (please complete the following information):**
 - Linux distribution: CentOS7
 - XALT Version: 3.0.1

Any help is greatly appreciated.

**Comment by rtmclay** [comment]
I can only recommend that you use an older version of MySQL.   Eventually, there will be a way to connect to MySQL from python, but the XALT team does not write that code.  As you know we use the mysqlclient with python3.  When that is updated or another python package is available we will update to that.

**Comment by KhanradCoder** [comment]
Awesome, thank you
