### ISSUE TITLE
mpi processes hangs when located in directory with space in its name.

### ISSUE THREAD

**Issue by mdong** [xalt/xalt#9]
Hi guys,

I noticed a small issue. As title, if launching an MPI process with space " " in its path anywhere would cause MPI process to hang. After some digging, I find the following line is causing the issue.

https://github.com/xalt/xalt/blob/faf05c6b9e91950dda167bd658fd28063bfca19e/src/Options.C#L185

I think a simple fix like below should be suffice.

```
-      cmd = "PATH=" XALT_SYSTEM_PATH " file " + m_exec;
+      cmd = "PATH=" XALT_SYSTEM_PATH " file '" + m_exec + "'"; 
```

Thanks for all the good work.

Best,
Min Dong

**Comment by rtmclay** [comment]
Thanks very much for reporting the bug and the proposed fix!  I am sure that it took some time to track the issue down. I appreciate your effort.

You are correct that your proposed fix would handle filenames with spaces in the name.  However, I realized that an executable name with double quotes would have a similar problem.  So I have updated XALT to support both spaces and double quotes.

If you get the chance, please test XALT 2.6.13 to see if it fixes your problem.  Thanks!

**Comment by mdong** [comment]
Thanks for the quick response!! I am very glad you took care names with " inside as well, I honestly cannot imagine how many of my script will break if there is such file ....

I am already on 2.6.13 for half of day now, everything seems to be good so far! 

Thanks again for all the good work.
